#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Garmin Connect sync script for GarminCoach HA Addon.

Pulls latest health data from Garmin Connect API and inserts into the
local PostgreSQL database. Runs periodically via the s6 service manager.

Supports two auth modes:
  1. Saved tokens in /data/garmin-tokens/ (preferred, from generate-garmin-tokens.py)
  2. Email/password from environment variables (fallback)
"""

import json
import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

try:
    from garminconnect import Garmin
except ImportError:
    print("ERROR: garminconnect not installed", file=sys.stderr)
    sys.exit(1)

try:
    import psycopg2
except ImportError:
    print("ERROR: psycopg2 not installed", file=sys.stderr)
    sys.exit(1)


DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://postgres@127.0.0.1:5432/garmincoach")
GARMIN_EMAIL = os.environ.get("GARMIN_EMAIL", "")
GARMIN_PASSWORD = os.environ.get("GARMIN_PASSWORD", "")
TOKEN_DIR = "/data/garmin-tokens"
# Must match the userId used by the Next.js app (DEV_BYPASS_AUTH seed user)
USER_ID = os.environ.get("GARMIN_USER_ID", "seed-user-001")

SYNC_STATUS_FILE = os.path.join(TOKEN_DIR, ".sync_status")


def _write_sync_status(phase, detail="", progress=0):
    """Write sync progress to a shared status file for the auth server."""
    import json as _json
    os.makedirs(TOKEN_DIR, exist_ok=True)
    status = {
        "syncing": True,
        "phase": phase,
        "detail": detail,
        "progress": progress,
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    try:
        with open(SYNC_STATUS_FILE, "w") as f:
            _json.dump(status, f)
    except Exception:
        pass


def _clear_sync_status():
    """Clear sync status file when sync completes."""
    import json as _json
    status = {
        "syncing": False,
        "phase": "idle",
        "detail": "",
        "progress": 100,
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    try:
        with open(SYNC_STATUS_FILE, "w") as f:
            _json.dump(status, f)
    except Exception:
        pass


def get_client():
    """Authenticate with Garmin Connect, preferring saved tokens."""
    os.makedirs(TOKEN_DIR, exist_ok=True)
    oauth1_path = os.path.join(TOKEN_DIR, "oauth1_token.json")
    oauth2_path = os.path.join(TOKEN_DIR, "oauth2_token.json")

    # Mode 1: Resume from saved garth tokens (generated by generate-garmin-tokens.py)
    if os.path.exists(oauth1_path) and os.path.exists(oauth2_path):
        try:
            client = Garmin(GARMIN_EMAIL or "token-user")
            client.login(tokenstore=TOKEN_DIR)
            # Re-save tokens (refreshes OAuth2 if needed)
            client.garth.dump(TOKEN_DIR)
            print("Authenticated with saved tokens")
            return client
        except Exception as e:
            print(f"Saved tokens failed: {e}", file=sys.stderr)
            print("Try re-running scripts/generate-garmin-tokens.py", file=sys.stderr)

    # Mode 2: Email/password login
    if GARMIN_EMAIL and GARMIN_PASSWORD:
        try:
            client = Garmin(GARMIN_EMAIL, GARMIN_PASSWORD)
            client.login()
            client.garth.dump(TOKEN_DIR)
            print("Authenticated with credentials, tokens saved")
            return client
        except Exception as e:
            print(f"Credential login failed: {e}", file=sys.stderr)

    return None


def get_db():
    """Connect to PostgreSQL."""
    return psycopg2.connect(DATABASE_URL)


def _safe_sleep_minutes(sleep_dto, key):
    """Safely extract sleep seconds and convert to minutes."""
    val = sleep_dto.get(key)
    if val is None:
        return None
    return val // 60


def _extract_sleep_time(sleep_dto, key):
    """Extract sleep timestamp and convert to minutes-from-midnight string."""
    ts = sleep_dto.get(key)
    if ts is None:
        return None
    try:
        # Garmin returns epoch milliseconds (local time)
        dt = datetime.fromtimestamp(ts / 1000)
        minutes = dt.hour * 60 + dt.minute
        return str(minutes)
    except (ValueError, TypeError, OSError):
        return None


def _compute_sleep_debt(sleep_dto):
    """Compute sleep debt = need - actual (in minutes). Positive = deficit."""
    need = sleep_dto.get("sleepNeedInMinutes")
    actual_sec = sleep_dto.get("sleepTimeSeconds")
    if need is None or actual_sec is None:
        return None
    actual_min = actual_sec // 60
    return need - actual_min


def sync_daily_stats(client, db, date_str):
    """Sync daily health stats for a given date."""
    cur = db.cursor()
    try:
        stats = client.get_stats(date_str)
        sleep_data = client.get_sleep_data(date_str)
        hrv = client.get_hrv_data(date_str)
        stress = client.get_stress_data(date_str)

        # Debug: log stress field names so we can verify data extraction
        stress_val = None
        if stress:
            stress_val = stress.get("avgStressLevel") or stress.get("averageStressLevel")
        if not stress_val and stats:
            stress_val = stats.get("averageStressLevel")
        if stress_val:
            print(f"  Stress score for {date_str}: {stress_val}")

        sleep_dto = sleep_data.get("dailySleepDTO", {}) if sleep_data else {}

        # Ensure unique constraint exists for upsert
        cur.execute("""
            DO $$ BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'daily_metric_user_date_uq'
                ) THEN
                    ALTER TABLE daily_metric
                        ADD CONSTRAINT daily_metric_user_date_uq
                        UNIQUE (user_id, date);
                END IF;
            END $$;
        """)

        cur.execute("""
            INSERT INTO daily_metric (
                user_id, date, steps, calories, resting_hr, max_hr,
                total_sleep_minutes, deep_sleep_minutes, rem_sleep_minutes,
                light_sleep_minutes, awake_minutes, sleep_score,
                hrv, stress_score, body_battery_start, body_battery_end,
                floors_climbed, intensity_minutes,
                sleep_start_time, sleep_end_time, sleep_need_minutes, sleep_debt_minutes,
                synced_at
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (user_id, date) DO UPDATE SET
                steps = EXCLUDED.steps,
                calories = EXCLUDED.calories,
                resting_hr = EXCLUDED.resting_hr,
                max_hr = EXCLUDED.max_hr,
                total_sleep_minutes = EXCLUDED.total_sleep_minutes,
                deep_sleep_minutes = EXCLUDED.deep_sleep_minutes,
                rem_sleep_minutes = EXCLUDED.rem_sleep_minutes,
                light_sleep_minutes = EXCLUDED.light_sleep_minutes,
                awake_minutes = EXCLUDED.awake_minutes,
                sleep_score = EXCLUDED.sleep_score,
                hrv = EXCLUDED.hrv,
                stress_score = EXCLUDED.stress_score,
                body_battery_start = EXCLUDED.body_battery_start,
                body_battery_end = EXCLUDED.body_battery_end,
                floors_climbed = EXCLUDED.floors_climbed,
                intensity_minutes = EXCLUDED.intensity_minutes,
                sleep_start_time = COALESCE(EXCLUDED.sleep_start_time, daily_metric.sleep_start_time),
                sleep_end_time = COALESCE(EXCLUDED.sleep_end_time, daily_metric.sleep_end_time),
                sleep_need_minutes = COALESCE(EXCLUDED.sleep_need_minutes, daily_metric.sleep_need_minutes),
                sleep_debt_minutes = COALESCE(EXCLUDED.sleep_debt_minutes, daily_metric.sleep_debt_minutes),
                synced_at = EXCLUDED.synced_at
        """, (
            USER_ID,
            date_str,
            stats.get("totalSteps"),
            stats.get("totalKilocalories"),
            stats.get("restingHeartRate"),
            stats.get("maxHeartRate"),
            _safe_sleep_minutes(sleep_dto, "sleepTimeSeconds"),
            _safe_sleep_minutes(sleep_dto, "deepSleepSeconds"),
            _safe_sleep_minutes(sleep_dto, "remSleepSeconds"),
            _safe_sleep_minutes(sleep_dto, "lightSleepSeconds"),
            _safe_sleep_minutes(sleep_dto, "awakeSleepSeconds"),
            sleep_dto.get("sleepScores", {}).get("overall", {}).get("value"),
            hrv.get("hrvSummary", {}).get("weeklyAvg") if hrv else None,
            (stress.get("avgStressLevel") or stress.get("averageStressLevel") or stats.get("averageStressLevel")) if stress else stats.get("averageStressLevel"),
            stats.get("bodyBatteryChargedValue"),
            stats.get("bodyBatteryDrainedValue"),
            stats.get("floorsAscended"),
            stats.get("intensityMinutesGoal"),
            _extract_sleep_time(sleep_dto, "sleepStartTimestampLocal"),
            _extract_sleep_time(sleep_dto, "sleepEndTimestampLocal"),
            sleep_dto.get("sleepNeedInMinutes"),
            _compute_sleep_debt(sleep_dto),
            datetime.now(timezone.utc).isoformat(),
        ))
        db.commit()
        print(f"  Synced daily stats for {date_str}")
    except Exception as e:
        db.rollback()
        print(f"  Failed to sync {date_str}: {e}", file=sys.stderr)
    finally:
        cur.close()


def sync_activities(client, db, days=7):
    """Sync activities, fetching in batches of 100."""
    cur = db.cursor()
    try:
        # Ensure unique constraint exists for upsert
        cur.execute("""
            DO $$ BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'activity_garmin_id_uq'
                ) THEN
                    ALTER TABLE activity
                        ADD CONSTRAINT activity_garmin_id_uq
                        UNIQUE (garmin_activity_id);
                END IF;
            END $$;
        """)

        total = 0
        batch_size = 100
        start = 0
        while True:
            activities = client.get_activities(start, batch_size)
            if not activities:
                break

            for act in activities:
                act_id = str(act.get("activityId", ""))
                # Extract HR zone minutes (seconds → minutes)
                hr_zones = None
                z1 = act.get("hrTimeInZone_1")
                if z1 is not None:
                    hr_zones = json.dumps({
                        "zone1": round((act.get("hrTimeInZone_1", 0) or 0) / 60, 1),
                        "zone2": round((act.get("hrTimeInZone_2", 0) or 0) / 60, 1),
                        "zone3": round((act.get("hrTimeInZone_3", 0) or 0) / 60, 1),
                        "zone4": round((act.get("hrTimeInZone_4", 0) or 0) / 60, 1),
                        "zone5": round((act.get("hrTimeInZone_5", 0) or 0) / 60, 1),
                    })

                # Compute TRIMP from avg HR and duration
                avg_hr = act.get("averageHR")
                duration_min = (act.get("duration", 0) or 0) / 60
                trimp = None
                if avg_hr and duration_min > 0:
                    # Simplified TRIMP: duration * intensity factor
                    hr_ratio = avg_hr / 200.0  # Normalized intensity
                    trimp = round(duration_min * hr_ratio * 0.64 * (1.92 ** hr_ratio), 1)

                avg_cadence = (
                    act.get("averageRunningCadenceInStepsPerMinute")
                    or act.get("averageBikingCadenceInRevPerMinute")
                )
                max_cadence = (
                    act.get("maxRunningCadenceInStepsPerMinute")
                    or act.get("maxBikingCadenceInRevPerMinute")
                )

                cur.execute("""
                    INSERT INTO activity (
                        user_id, garmin_activity_id, sport_type, sub_type,
                        started_at, duration_minutes, distance_meters,
                        avg_hr, max_hr, calories, avg_pace_sec_per_km,
                        aerobic_te, anaerobic_te, hr_zone_minutes,
                        trimp_score, strain_score,
                        avg_power, normalized_power, max_power,
                        avg_cadence, max_cadence,
                        synced_at, raw_garmin_data
                    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (garmin_activity_id) DO UPDATE SET
                        hr_zone_minutes = COALESCE(EXCLUDED.hr_zone_minutes, activity.hr_zone_minutes),
                        trimp_score = COALESCE(EXCLUDED.trimp_score, activity.trimp_score),
                        strain_score = COALESCE(EXCLUDED.strain_score, activity.strain_score),
                        avg_power = COALESCE(EXCLUDED.avg_power, activity.avg_power),
                        normalized_power = COALESCE(EXCLUDED.normalized_power, activity.normalized_power),
                        max_power = COALESCE(EXCLUDED.max_power, activity.max_power),
                        avg_cadence = COALESCE(EXCLUDED.avg_cadence, activity.avg_cadence),
                        max_cadence = COALESCE(EXCLUDED.max_cadence, activity.max_cadence),
                        synced_at = EXCLUDED.synced_at,
                        raw_garmin_data = EXCLUDED.raw_garmin_data
                """, (
                    USER_ID,
                    act_id,
                    act.get("activityType", {}).get("typeKey", "other"),
                    act.get("activityType", {}).get("typeId", ""),
                    act.get("startTimeLocal"),
                    duration_min,
                    act.get("distance"),
                    avg_hr,
                    act.get("maxHR"),
                    act.get("calories"),
                    act.get("averageSpeed"),
                    act.get("aerobicTrainingEffect"),
                    act.get("anaerobicTrainingEffect"),
                    hr_zones,
                    trimp,
                    act.get("activityTrainingLoad"),
                    act.get("averagePower"),
                    act.get("normPower"),
                    act.get("maxPower"),
                    avg_cadence,
                    max_cadence,
                    datetime.now(timezone.utc).isoformat(),
                    json.dumps(act),
                ))
            db.commit()
            total += len(activities)
            print(f"  Synced batch: {len(activities)} activities (total: {total})")

            if len(activities) < batch_size:
                break
            start += batch_size

            # Incremental syncs: stop after enough recent activities
            if days <= 30 and total >= 50:
                break

        print(f"  Synced {total} activities total")
    except Exception as e:
        db.rollback()
        print(f"  Failed to sync activities: {e}", file=sys.stderr)
    finally:
        cur.close()


def backfill_from_raw_json(db):
    """Extract hr_zone_minutes, strain_score, trimp_score from stored raw_garmin_data."""
    cur = db.cursor()
    try:
        cur.execute("""
            SELECT id, raw_garmin_data, avg_hr, duration_minutes
            FROM activity
            WHERE user_id = %s
              AND raw_garmin_data IS NOT NULL
              AND (hr_zone_minutes IS NULL OR strain_score IS NULL)
        """, (USER_ID,))
        rows = cur.fetchall()
        if not rows:
            return

        updated = 0
        for row_id, raw_json, avg_hr, duration_min in rows:
            act = json.loads(raw_json) if isinstance(raw_json, str) else raw_json

            # Extract HR zones (seconds → minutes)
            hr_zones = None
            z1 = act.get("hrTimeInZone_1")
            if z1 is not None:
                hr_zones = json.dumps({
                    "zone1": round((act.get("hrTimeInZone_1", 0) or 0) / 60, 1),
                    "zone2": round((act.get("hrTimeInZone_2", 0) or 0) / 60, 1),
                    "zone3": round((act.get("hrTimeInZone_3", 0) or 0) / 60, 1),
                    "zone4": round((act.get("hrTimeInZone_4", 0) or 0) / 60, 1),
                    "zone5": round((act.get("hrTimeInZone_5", 0) or 0) / 60, 1),
                })

            # Garmin training load
            strain = act.get("activityTrainingLoad")

            # Compute TRIMP if we have HR data
            trimp = None
            if avg_hr and duration_min and duration_min > 0:
                hr_ratio = avg_hr / 200.0
                trimp = round(duration_min * hr_ratio * 0.64 * (1.92 ** hr_ratio), 1)

            if hr_zones or strain or trimp:
                cur.execute("""
                    UPDATE activity SET
                        hr_zone_minutes = COALESCE(%s, hr_zone_minutes),
                        strain_score = COALESCE(%s, strain_score),
                        trimp_score = COALESCE(%s, trimp_score)
                    WHERE id = %s
                """, (hr_zones, strain, trimp, row_id))
                updated += 1

        db.commit()
        if updated:
            print(f"  Backfilled {updated} activities with zones/strain/TRIMP")
    except Exception as e:
        db.rollback()
        print(f"  Backfill failed: {e}", file=sys.stderr)
    finally:
        cur.close()


def backfill_stress_and_sleep(client, db):
    """One-time backfill: re-fetch stress and sleep timing for dates with NULL values."""
    MARKER = os.path.join(TOKEN_DIR, ".stress_sleep_backfill_done")
    if os.path.exists(MARKER):
        return

    cur = db.cursor()
    try:
        cur.execute("""
            SELECT date FROM daily_metric
            WHERE user_id = %s
              AND (stress_score IS NULL OR sleep_start_time IS NULL)
            ORDER BY date DESC
            LIMIT 365
        """, (USER_ID,))
        dates = [row[0] for row in cur.fetchall()]
        if not dates:
            Path(MARKER).touch()
            return

        print(f"  Backfilling stress/sleep for {len(dates)} dates...")
        filled = 0
        for date_str in dates:
            try:
                stress = client.get_stress_data(date_str)
                sleep_data = client.get_sleep_data(date_str)
                stats = client.get_stats(date_str)
                sleep_dto = sleep_data.get("dailySleepDTO", {}) if sleep_data else {}

                stress_val = None
                if stress:
                    stress_val = stress.get("avgStressLevel") or stress.get("averageStressLevel")
                if not stress_val and stats:
                    stress_val = stats.get("averageStressLevel")

                sleep_start = _extract_sleep_time(sleep_dto, "sleepStartTimestampLocal")
                sleep_end = _extract_sleep_time(sleep_dto, "sleepEndTimestampLocal")
                sleep_need = sleep_dto.get("sleepNeedInMinutes")
                sleep_debt = _compute_sleep_debt(sleep_dto)

                cur.execute("""
                    UPDATE daily_metric SET
                        stress_score = COALESCE(%s, stress_score),
                        sleep_start_time = COALESCE(%s, sleep_start_time),
                        sleep_end_time = COALESCE(%s, sleep_end_time),
                        sleep_need_minutes = COALESCE(%s, sleep_need_minutes),
                        sleep_debt_minutes = COALESCE(%s, sleep_debt_minutes)
                    WHERE user_id = %s AND date = %s
                """, (stress_val, sleep_start, sleep_end, sleep_need, sleep_debt,
                      USER_ID, date_str))
                if stress_val or sleep_start:
                    filled += 1
            except Exception:
                pass  # skip individual date failures

        db.commit()
        Path(MARKER).touch()
        print(f"  Backfilled stress/sleep for {filled}/{len(dates)} dates")
    except Exception as e:
        db.rollback()
        print(f"  Stress/sleep backfill failed: {e}", file=sys.stderr)
    finally:
        cur.close()


def sync_vo2max(client, db, days=7):
    """Sync VO2max from Garmin's official max-metrics API, with computed fallback."""
    cur = db.cursor()
    try:
        # Ensure unique constraint exists for upsert
        cur.execute("""
            DO $$ BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'vo2max_estimate_user_date_sport_uq'
                ) THEN
                    ALTER TABLE vo2max_estimate
                        ADD CONSTRAINT vo2max_estimate_user_date_sport_uq
                        UNIQUE (user_id, date, sport);
                END IF;
            END $$;
        """)

        # Note: we no longer bulk-delete computed records. The per-date
        # fallback logic below uses ON CONFLICT to update only dates that
        # lack official Garmin data, preserving existing Uth estimates for
        # historical dates outside the current sync window.
        db.commit()

        cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).date()
        today = datetime.now(timezone.utc).date()

        # --- Primary: Garmin's official VO2max from max-metrics API ---
        garmin_count = 0
        try:
            d = cutoff
            while d <= today:
                date_str = d.isoformat()
                try:
                    metrics = client.get_max_metrics(date_str)
                except Exception:
                    d += timedelta(days=1)
                    continue

                if not metrics:
                    d += timedelta(days=1)
                    continue

                # get_max_metrics returns a list of metric entries
                entries = metrics if isinstance(metrics, list) else [metrics]
                for entry in entries:
                    vo2 = entry.get("generic", {}).get("vo2MaxPreciseValue") \
                        or entry.get("generic", {}).get("vo2MaxValue")
                    sport = "general"

                    if not vo2:
                        # Try cycling-specific
                        vo2 = entry.get("cycling", {}).get("vo2MaxPreciseValue") \
                            or entry.get("cycling", {}).get("vo2MaxValue")
                        if vo2:
                            sport = "cycling"

                    if not vo2:
                        continue

                    vo2 = float(vo2)
                    if vo2 < 10 or vo2 > 90:
                        continue

                    metric_date = entry.get("calendarDate", date_str)
                    cur.execute("""
                        INSERT INTO vo2max_estimate (
                            user_id, date, sport, value, source
                        ) VALUES (%s, %s, %s, %s, %s)
                        ON CONFLICT (user_id, date, sport) DO UPDATE SET
                            value = EXCLUDED.value,
                            source = EXCLUDED.source
                    """, (USER_ID, metric_date, sport, round(vo2, 1), "garmin_official"))
                    garmin_count += 1

                if garmin_count % 50 == 0 and garmin_count > 0:
                    db.commit()
                d += timedelta(days=1)

            db.commit()
        except Exception as e:
            print(f"  Garmin max-metrics API failed: {e} — falling back to computed")
            db.rollback()

        # --- Fallback: computed VO2max only for dates missing official data ---
        # Only compute Uth estimates for specific dates where the Garmin API
        # returned no data, rather than the previous all-or-nothing approach.
        # This prevents overwriting good official data when the API partially fails.
        cur2 = db.cursor()
        try:
            # Find dates in the sync window that have no garmin_official record
            cur2.execute("""
                SELECT dm.date, dm.resting_hr
                FROM daily_metric dm
                WHERE dm.user_id = %s AND dm.date >= %s
                  AND dm.resting_hr IS NOT NULL AND dm.resting_hr > 30
                  AND dm.resting_hr <= 100
                  AND NOT EXISTS (
                      SELECT 1 FROM vo2max_estimate ve
                      WHERE ve.user_id = dm.user_id
                        AND ve.date = dm.date
                        AND ve.source = 'garmin_official'
                  )
                ORDER BY dm.date DESC
            """, (USER_ID, cutoff.isoformat()))

            # Use fetchmany() batching to handle large sync windows gracefully
            missing_dates: list[tuple] = []
            while True:
                rows = cur2.fetchmany(500)
                if not rows:
                    break
                missing_dates.extend(rows)

            uth_count = 0

            if missing_dates:
                # Fetch user age for age-predicted max HR
                cur2.execute("SELECT age FROM profile WHERE user_id = %s", (USER_ID,))
                age_row = cur2.fetchone()
                user_age = age_row[0] if age_row and age_row[0] else 35
                if not (age_row and age_row[0]):
                    print("  No age in profile — using default age=35")

                age_predicted_max_hr = 220 - user_age

                for d_date, resting_hr in missing_dates:
                    vo2 = 15.3 * (age_predicted_max_hr / resting_hr)
                    if vo2 < 20 or vo2 > 90:
                        continue
                    cur2.execute("""
                        INSERT INTO vo2max_estimate (
                            user_id, date, sport, value, source
                        ) VALUES (%s, %s, %s, %s, %s)
                        ON CONFLICT (user_id, date, sport) DO UPDATE SET
                            value = EXCLUDED.value, source = EXCLUDED.source
                    """, (USER_ID, d_date, "general", round(vo2, 1), "uth_method"))
                    uth_count += 1
                db.commit()

            print(
                f"  VO2max: {garmin_count} official Garmin records, "
                f"{uth_count} Uth fallback estimates "
                f"(for dates without official data)"
            )
        finally:
            cur2.close()
    except Exception as e:
        db.rollback()
        print(f"  Failed to sync VO2max: {e}", file=sys.stderr)
    finally:
        cur.close()


def main():
    has_tokens = (
        os.path.exists(os.path.join(TOKEN_DIR, "oauth1_token.json"))
        and os.path.exists(os.path.join(TOKEN_DIR, "oauth2_token.json"))
    )

    if not has_tokens and (not GARMIN_EMAIL or not GARMIN_PASSWORD):
        print("No Garmin tokens or credentials configured, skipping sync")
        _clear_sync_status()
        return

    print(f"Starting Garmin sync at {datetime.now(timezone.utc).isoformat()}")
    _write_sync_status("starting", "Authenticating with Garmin...")
    client = get_client()
    if client is None:
        print("Failed to authenticate with Garmin, skipping sync", file=sys.stderr)
        _clear_sync_status()
        return

    # First sync: full history from 2019. Subsequent syncs: 7 days only.
    HISTORY_MARKER = os.path.join(TOKEN_DIR, ".initial_sync_done")
    if os.path.exists(HISTORY_MARKER):
        sync_days = 7
    else:
        # Calculate days from 2019-01-01 to today
        epoch = datetime(2019, 1, 1, tzinfo=timezone.utc).date()
        today = datetime.now(timezone.utc).date()
        sync_days = (today - epoch).days
        print(f"First sync — pulling {sync_days} days of history (from 2019-01-01)...")

    db = get_db()

    today = datetime.now(timezone.utc).date()
    for days_ago in range(sync_days):
        date_str = (today - timedelta(days=days_ago)).isoformat()
        _write_sync_status("daily_stats", f"Syncing {date_str}",
                           int((days_ago / sync_days) * 50))
        sync_daily_stats(client, db, date_str)

    # Garmin API: get_activities(start, limit) — fetch in batches of 100
    _write_sync_status("activities", "Syncing activities...", 50)
    sync_activities(client, db, days=sync_days)

    # Backfill computed fields from raw Garmin JSON
    _write_sync_status("backfill", "Computing zones & strain...", 80)
    backfill_from_raw_json(db)

    _write_sync_status("backfill_stress", "Backfilling stress & sleep timing...", 85)
    backfill_stress_and_sleep(client, db)

    _write_sync_status("vo2max", "Computing VO2max estimates...", 90)
    sync_vo2max(client, db, days=sync_days)

    db.close()

    # Mark initial sync complete
    if not os.path.exists(HISTORY_MARKER):
        with open(HISTORY_MARKER, "w") as f:
            f.write(datetime.now(timezone.utc).isoformat())

    _clear_sync_status()
    print("Garmin sync complete")


if __name__ == "__main__":
    main()
